name: actions
author: Keys
description: Compile LaTeX document
runs:
  using: 'composite'
  steps:
    - name: Compile LateX
      uses: vinay0410/tectonic-action@v1.1.2
      with:
        tex_path: 'paper/main.tex'
