name: Build LaTeX
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX (latexmk)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: paper/main.tex
          working_directory: .
          latexmk_use_xelatex: false
          latexmk_shell_escape: true